version: '2'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PWD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PWD
    volumes:
      - msql-data:/var/lib/msql
  pma:
    image: phpmyadmin:latest
    ports: 
      - 9000:80
    environment:
      - PMA_HOST=mysql
volumes:
  msql-data:
    driver: local